title: Rahat Hosen
description: Full Stack Developer
baseurl: "/rahathosen/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "rahathosen.me@gmail.com"
linkedin: "http://linkedin.com/in/rahathosen"
github: "https://github.com/rahathosen"
website: "http://rahathosen.github.io/"
medium: "https://rahathosen.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
